project:
  type: website
  output-dir: docs

website:
  title: "Statistical Computing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sas.qmd
        text: SAS
      - href: sql.qmd
        text: SQL
      - href: g_hub.qmd
        text: GitHub
      - href: VS_Code.qmd
        text: VS Code

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

