---
title: "GitHub Handbook"
format: html
editor: visual
---

This handbook preliminarily follows the YouTube video [Git & GitHub Crash Course for Beginners](https://www.youtube.com/watch?v=mAFoROnOfHs&t=241s)

## GiT iNiT

GitHub claims it tracks when changed, what changed, who changed, and where those happened. If not downloaded, download the GitHub. I comes with another app called Git Bash. Usually both Git and Git Bash are installed in Windows computer. So, you can open the Git Bash app.

``` python
# To check the version
git --version

# To go to your directory
cd Desktop/Git_try
# Some other common commands are pwd, mkdir

# Create three files, which we will keep track in future
touch one.txt
touch two.txt
mkdir my_folder # I want to save the third document in another folder
cd my_folder
touch three.txt

# .. will take back to the previous folder
cd ..

# You can make some changes to the documents. Or, you may want to save the current files and keep track of these files
# Make sure you are on the correct folder you can to keep track of

git init
```

The last command will initialize the tacking by git.

``` python
# If you want to check the git file
ls -la # This shows the hidden files also
```

## Remote repository

Now if you want to save those files on the cloud for couple of reasons, e.g., to share your files with others, to get access from another computers, you need to upload them to a remote repository aka github.

Steps are: go to github-\> Click the New-\> Name the new repository-\> Create repository

You can create or upload files into the github. So, may want to download this repository to you local computer. Here to mention, this repository is an independent one. This one has no relation with the one we discussed in the last section. Sometimes, we start with files shared by others through the github repository. To download a repository, go to the folder you want to download.

``` python
# I was in the git_try folder
# I don't want to download there.
# Instead, I wan to download to the Desktop
cd .. # This takes back to the prior folder

# copy the url link you get after pressin <> Code, the greee button, in github
git clone https://github.com/mohishafique/another_try.git

cd another_try
ls -la
# This will show another git file, which indicates git is tracking the file
```

## Status, Add, Reset, and Commit

After changing the folder, we need to check the status of the folder, to add or reset the folder.

``` python
git status
git add --all # alternative is git add -A
# git add . seems to do the same. However, it stages the file someone is currently at. It doesn't stage files of the parent folders.

git reset # This unstaged or unadded all the files 
git reset HEAD~ # This takes back to the previous status before the last commit
git reset --hard # Normal reset only unstage the files, but it doesn't bring back the deleted files. To bring back the deleted file --hard is needed. 

git add --all
git commit -m "adding a new folder"

# If this is the first commit, then you may need to do
git config --global user.email "your_email"
git config --global user.name "your_name"
```

## Git Log

Git log is the most important command for knowing different versions.

``` python
# To know the history
git log

# To know only the summary about the history
git log --oneline
```

When we talk about different versions and version control, branching comes. Branching is another important idea in git.

``` python
# To know about existing branches
git branch

# To create a new branch
git branch developement #developement is the given name
```

When a git branch is created, it exactly copies the current branch at the time of creation. After the creation, we need to switch to that created branch if we want to make changes to that version.

``` python
# entering into the branch
git checkout developement

# Now you can add a file to that folder
# Then stage it using git add command
git add .
# Finally, commit the changes
git commit -m 'five.txt file added'

# Now if you switch to the main brach,
# surprisingly, you won't see the five.txt
git checkout main
ls
# not any five.txt file shown
```

Suppose one person is working in the main branch. Another person copies that and does additional updates to the folder. By the meantime, new changes have been made in the main branch. Now, both folders have different updates. Unless both folders have changed the same named files, it is better to merge the main branch to the new branch. And finally, new branch should be merged to the main one.

``` python
# changes have been made in the second branch developement
# Now, go to main branch and make some changes
git checkout main

# after some changes
git add .
git commit -m 'one.txt has been changed'

git checkout developement
git merge main -m "merging main into the developement branch"

git checkout main
git merge developement -m "merging developement to main"
```

If changes have been happened in the same file of different branches and we want to merge those two branches, then auto merge will fail. Then you need to open the conflicting file manually and select the version you want. After having the desired modification, you need to add and commit the new changes as per usual rules.

Using commit ids as branch name creates ample opportunities in the era of version control.

``` python
# bring the log history
git log --oneline

# going back to past
git checkout 6cbc4ea # This is the commit ID

# I need to explore little bit more about the following prompt
# If you want to create a new branch to retain commits you create, you may
# do so (now or later) by using -c with the switch command. Example:
# 
#   git switch -c <new-branch-name>
# 
# Or undo this operation with:
# 
#   git switch -

# git switch -c <new-branch-name>
# # is equivalent to 
# git branch <new-branch-name>
# git switch <new-branch-name>
```

To learn about the differences about two commits:

``` python
git diff new-branch old-branch

# one last quick tip
git log
# This will open a new terminal
q # press q to close the terminal
```

## Remote repository or GitHub

It is surprising that if you download the git repository from github and work on the folder, the system remembers the remote github repository. Therefore the following command is enough to upload the adjustment made in the local repository.

``` python
git push origin main

# or if you want to create a new branch in github 
git push origin developement

# Similarly git fetch
git fetch
git merge

# git pull in the combination of git ferch and git merge
git pull # git pull = git fetch + git merge
```
