---
title: "SAS Handbook"
---

# Learn the Basics of SAS Programming

This Chapter initially follows the instructions from the video: [Learn the basics of SAS Programming](https://www.youtube.com/watch?v=vQZ0DSUTAzQ)

``` sass
/*For commenting */
or 
*For inline comment;
```

Columns are called 'Variables' and rows are called 'Observations'. Character variables are left indented and the Numeric variables are right indented. Missing data for the character variables will be denoted by blanks and for the numerical variables will be denoted by the '.'. On the left side menu of the SAS_ondemand, there is a folder called Libraries. In that Libraries folder, there is another sub-folder called SASHELP. In this sashelp, there are some saved data files. It is the easiest to work with these saved data sets to learn about SAS.

SAS has separated the codes into two steps. One is called the Data step and the another is called the Proc step. In the data step, we mainly manipulate the data. To understand the set statement, we need to understand the set-up of libraries. SAS organizes the data sets in libraries. You can think of data sets as books, and certain books may belong to certain libraries. So, there are multiple libraries in SAS, such as SASHELP, SASUSER, WORK, etc. Here, the WORK library stores the temporary data sets. Now, let's try to understand the codes below.

``` sass
DATA female_class_report; *naming the generated data set. It will be save to the temporary data library WORK;
    set sashelp.class; *This will bring the class data from sashelp library;
    if sex = 'F'; *This writes to the log;
    put 'report for female students only';
run;
```

## Creating Folders and Libraries

There might be some reasons for creating a folder.

-   Saving your codes to a particular folder in an organized way for a project

-   Uploading your data-set to a folder

-   Importing an uploaded data-set

-   Saving your modified new data-set to a particular folder

Creating a folder is pretty straightforward by using your mouse. After creating a folder, you may fulfill the above objectives.

**Saving your codes to a particular folder:** Your code scripts can be created by Mouse Right Click-\> New-\> SAS Program (F4). Then write your sas program in the script. Then save it pressing ctrl+s. A pop-up menu will show up where you can set your desired folder as the script's location.

**Uploading data-sets to a particular folder:** First talk about uploading a data-set, which is straightforward. Go to your desired folder-\> Mouse Right Click-\> Upload Files...-\> Choose Files

**Importing and Exporting a data-set:** Although creating a folder isn't the reason for importing a data-set to the sas working environment. However, we import a data to the environment from a folder. Therefore, it is better to talk the steps in this section. The easiest way to import the data is to go to the Uploaded data-\> Import-\> Copy the code (change the new name of the data-set if necessary).

``` sass
/* Generated Code (IMPORT) */
/* Source File: diabetic_data.csv */
/* Source Path: /home/u62633132/Class_data */
/* Code generated on: 1/22/26, 4:39 PM */

%web_drop_table(WORK.IMPORT);


FILENAME REFFILE '/home/u62633132/Class_data/diabetic_data.csv';

PROC IMPORT DATAFILE=REFFILE
    DBMS=CSV
    OUT=WORK.IMPORT;
    GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.IMPORT; RUN;


%web_open_table(WORK.IMPORT); 
```

The easiest way to exporting a data-set will be: go to the data-set in a particular library-\> Right click -\> Export.

**Saving your modified new data-set to a particular folder:** Created data sets are temporarily saved in the WORK library. However, if we need to permanently save our created data sets, then we need to save it in a folder through creating a library. So, it is a two step process:

-   **Creating a library and connecting the library to the folder:** In this step, we need to define a library and connect that library to a folder so that whatever data-set we put in that library will automatically be stored in that folder. So, we need to know the path of the folder. We get get that by 'Server Files and the Folders' -\> 'Your_folder' -\> Properties option -\> copy the location. Then run a similar code to create a library called my_lib:

    ``` sass
    libname my_lib '/home/u62633132/Class_data' ;
    run;
    ```

-   **Saving a modified data-set to a folder:** The only thing is you need to mention the library name which is connected to your desired folder.

    ``` sass
    data my_lib.my_class_data;
      set sashelp.class;
    run;
    ```

## Typing a New Data

Although as a statistician we often don't need to type the data-set, the knowledge is needed for creating new variables.

``` sass
data test_data;
  input Name $ Height Weight; *input is used to declare variable name and $ on the right of the variable is used to indicate it's a character variable;
  dataline; *This line declares we are inputting data;
  Ben 154 182
  Pablo 172 155
  Jen 160 140
  ;
  run;
```

Or you can use the column numbers to input the data:

``` sass
data test_data;
  input Name $1-6 Height 7-9 Weight 11-13; *input is used to declare variable name and $ on the right of the variable is used to indicate it's a character variable;
  dataline; *This line declares we are inputting data;
  Ben   154 182
  Pablo 172 155
  Jen   160 140
  ;
  run;
```

The last important thing is to learn about the Informats. Sometimes, we need to input special characters, such as dollar sign or /, for inputting data-sets.

``` sass
data customer_trans;
  input Price DOLLAR6. Region $ Date MMDDYY10.;
  datalines;
$54.15 NW 01/01/2003
$62.38 SW 04/13/2003
$82.55 NE 06/15/2003
;
run;
```

To learn about the different informats, check the book (or any other resources?)\
\
But the output from above will be little bit funky. To solve the issue, we need to use the format command. So, the informat and format command may come together.

``` sass
data customer_trans;
  format Date MMDDYY10.;
  input Price DOLLAR6. Region $ Date MMDDYY10.;
  datalines;
$54.15 NW 01/01/2003
$62.38 SW 04/13/2003
$82.55 NE 06/15/2003
;
run;
```

We can also define our new formats using the proc format command.

``` sass
proc format;
  value $gender 'M' = 'Male'
                'F' = 'Female';
  value level 11 12 = 'Pre-Teen'
              13 - HIGH = 'Teen';
run;

Proc print data = sashelp.class;
  format sex $gender. Age level.;
run;
```

## Proc Contents

To learn about a data-set, proc contents can help.

``` sass
*Data manupulation in SAS;
proc contents data = sashelp.baseball varnum; *varnum shows in dataset orders;
run;

*if someone wants only the name and the lebels;
proc contents data = sashelp.baseball out = contents_out (keep = name label varnum) noprint;
run;

proc sort data = contents_out;
by varnum;
run;

proc print data=contents_out label;
  title "Variable names and labels";
run;

*printing the first couple of rows;
proc print data = sashelp.baseball (obs=3);
run;

*sql code doesn't need the parentheses;
proc sql outobs=4;
select *
from sashelp.baseball;
quit;

*If someone needs only the row and column numbers;
proc sql;
  select nobs, nvar
  from dictionary.tables
  where libname='SASHELP' and memname='BASEBALL';
quit;

ods select Attributes;        /* show only the Attributes (summary) table */
proc contents data=SASHELP.BASEBALL; run;
ods select all;              /* restore normal ODS selection */

*Exporting a dataset;
proc contents data = sashelp.baseball out = cont_out (keep = name label varnum) noprint;
run;

proc sort data = cont_out;
by varnum;
run;

proc export data = cont_out 
	outfile= "/home/u62633132/STAT_771/STAT_771_Data/cont_out.xlsx"
	dbms=xlsx
	replace;
run;
```

## Conditional Statements

``` sass
data fish_new;
    length fish_size $10; *length command is used instead of input command;
    set sashelp.fish;
    if length1 < 10 then fish_size = 'small';
    else fish_size = 'others';
run;
```

The above length command is not necessary. But it will not allow more than 8 characters. So, if someone needs more than 8 characters, it is important to define the length of the new variable by that length command. The only problem is it will bring the new variable at the beginning of the data-set.

Now, if we need to do multiple tasks based on an if condition, we need to use 'If Then Do;' instead of 'If Then' command.

``` sass
data fish_new;
    length fish_size $10;
    length fish_location $12;
    set sashelp.fish;
    
    if length1 < 10 then do;
    fish_size = 'small';
    fish_location = 'salt water';
    end;
    
    if length1 >= 10 then do;
    fish_size = 'others';
    fish_location = 'others';
    end;
    
run;
```

## Some Proc Commands

Learning about the summary of the data:

``` sass
Proc contents data = sashelp.air;
run;
```

Sorting your data:

``` sass
proc sort data = sashelp.cars out = cars; *Use out option because you cannot overwrite some library, such as sashelp;
by Make;
run;
```

Printing a data:

``` sass
Proc print data = cars;
  var Type Invoice Make Model;
run;
```

Making summary:

``` sass
Proc print data = cars;
  var Type Invoice Make Model;
  by Type;
  sum Invoice;
  title 'Cars Total Invoice by Type';
run;
```

## Proc Means

Getting the summary of a numerical variable:

``` sass
proc means data = sashelp.baseball mean median stddev max min maxdec=2; *maxdec=2 will print upto two decimal points;
    class div; *If we want to summarize based on a categorical variable;
    var crhits;
run;
```

# SAS Macros

This section is the summary of the video [playlist:](https://www.youtube.com/watch?v=Go1SHJPnjgM&list=PLXledyz7GVuJ9qwnEY1jAbo1uPnjARDGG&index=4)

## Types of Macros

-   **Global Macro:** Can be accessed by any SAS program.

-   **Local:** Only for the SAS program you are currently working on.

Macros can be used by the '&' sign.

``` sass
data _null_;
    put "Today's date is &sysdate";
run;
*This will print;
*Today's date is 01FEB26;
```

Local macros can be written using '%Let' systex.

``` sass
%Let car_make = 'Acura';

data make_analysis;
    set sashelp.cars;
    if Make = &car_make;
run;
```

## Macro Programs and Others

These macro programs start with %Macro and end with %Mend.

``` sass
%Macro bar_chart(char_var);
proc sgplot data = sashelp.cars;
  hbar &char_var;
run;
%MEND;

%bar_chart(origin);
```

There are two ways to use the put syntax.

``` sass
*If we only want to print a macro variable value;
%put %sysday

*However, if we use inside the data or proc steps, it will act like a print statement;
data _null_;
  a = 4;
  b = 3;
  c = a*b;
  put c=;
run;

*To see all the macros;
%put _USER_;
```

# Basic Reference

[cheatsheet](https://www.sas.com/content/dam/SAS/documents/technical/certification/exam-content/base-programming-ref-sheet.pdf)
